DROP TABLE IF EXISTS noteful_notes

CREATE TABLE noteful_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT,
    content TEXT,
    folder_id INTEGER REFERENCES noteful_folders(id) NOT NULL

);